#!/bin/bash

echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/" > ./filenametags.total
find . -type f \( \
	-name "*.[ch]" -o \
	-name "*.[sS]" -o \
	-name "*.[ch]pp" -o \
	-name "*.[ch]xx" -o \
	-name "*.[CH]" -o \
	-name "*.cc" -o \
	-name "*.java" -o \
	-name "*.xml" \
\) -printf "%f\t%p\t1\n" | sort -f >> filenametags.total

if [ "$1" == "kernel" ]; then
	# for CPU architecture specific files, just add arch/arm/* in the file list
	grep -v "arch/alpha/" ./filenametags.total | \
	grep -v "arch/avr32/" | \
	grep -v "arch/blackfin/" | \
	grep -v "arch/cris/" | \
	grep -v "arch/c6x/" | \
	grep -v "arch/frv/" | \
	grep -v "arch/h8300/" | \
	grep -v "arch/hexagon/" | \
	grep -v "arch/ia64/" | \
	grep -v "arch/m32r/" | \
	grep -v "arch/m68k/" | \
	grep -v "arch/m68knommu/" | \
	grep -v "arch/microblaze/" | \
	grep -v "arch/mips/" | \
	grep -v "arch/mn10300/" | \
	grep -v "arch/openrisc/" | \
	grep -v "arch/parisc/" | \
	grep -v "arch/powerpc/" | \
	grep -v "arch/s390/" | \
	grep -v "arch/score/" | \
	grep -v "arch/sh/" | \
	grep -v "arch/sparc/" | \
	grep -v "arch/tile/" | \
	grep -v "arch/um/" | \
	grep -v "arch/unicore32/" | \
	grep -v "arch/x86/" | \
	grep -v "arch/xtensa/" > ./filenametags
else
	cp ./filenametags.total ./filenametags
fi

rm -f ./filenametags.total

